### ISSUE TITLE
能多张图片预览吗?

### ISSUE THREAD

**Issue by zoubeihua** [heyongsheng/hevue-img-preview#2]
想传一个数组进去可以实现多张图片第地址预览

**Comment by heyongsheng** [comment]
抱歉，这个暂时不支持，这周末有时间我会加上这个功能

**Comment by zoubeihua** [comment]
好的期待

**Comment by zoubeihua** [comment]
> 抱歉，这个暂时不支持，这周末有时间我会加上这个功能
期待

**Comment by heyongsheng** [comment]
哈哈，我的多图预览加上了，不过估计你也不需要了，不过还是通知你一声


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"zoubeihua"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月4日(星期四) 中午12:45
收件人:&nbsp;"heyongsheng/hevue-img-preview"<hevue-img-preview@noreply.github.com&gt;;
抄送:&nbsp;"落叶"<1378431028@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [heyongsheng/hevue-img-preview] 能多张图片预览吗? (#2)





  
抱歉，这个暂时不支持，这周末有时间我会加上这个功能
 期待

**Comment by zoubeihua** [comment]
太感谢了，我需要呢&nbsp; 怎么找不到地址了呢&nbsp; &nbsp;能发我下吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "heyongsheng"<notifications@github.com&gt;; 
发送时间: 2020年6月15日(星期一) 下午3:08
收件人: "heyongsheng/hevue-img-preview"<hevue-img-preview@noreply.github.com&gt;; 
抄送: "邹倍华"<240917020@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [heyongsheng/hevue-img-preview] 能多张图片预览吗? (#2)





 哈哈，我的多图预览加上了，不过估计你也不需要了，不过还是通知你一声 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:&amp;nbsp;&quot;zoubeihua&quot;<notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年6月4日(星期四) 中午12:45 
 收件人:&amp;nbsp;&quot;heyongsheng/hevue-img-preview&quot;<hevue-img-preview@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;&quot;落叶&quot;<1378431028@qq.com&amp;gt;;&quot;Comment&quot;<comment@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [heyongsheng/hevue-img-preview] 能多张图片预览吗? (#2) 
 
 
 
 
 
    
 抱歉，这个暂时不支持，这周末有时间我会加上这个功能 
  期待 
    
 — 
 You are receiving this because you commented. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
&mdash;

**Comment by heyongsheng** [comment]
https://github.com/heyongsheng/hevue-img-preview




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "zoubeihua"<notifications@github.com&gt;; 
发送时间: 2020年6月19日(星期五) 下午3:17
收件人: "heyongsheng/hevue-img-preview"<hevue-img-preview@noreply.github.com&gt;; 
抄送: "落叶"<1378431028@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [heyongsheng/hevue-img-preview] 能多张图片预览吗? (#2)





 太感谢了，我需要呢&amp;nbsp; 怎么找不到地址了呢&amp;nbsp; &amp;nbsp;能发我下吗 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: &quot;heyongsheng&quot;<notifications@github.com&amp;gt;;  
 发送时间: 2020年6月15日(星期一) 下午3:08 
 收件人: &quot;heyongsheng/hevue-img-preview&quot;<hevue-img-preview@noreply.github.com&amp;gt;;  
 抄送: &quot;邹倍华&quot;<240917020@qq.com&amp;gt;; &quot;Author&quot;<author@noreply.github.com&amp;gt;;  
 主题: Re: [heyongsheng/hevue-img-preview] 能多张图片预览吗? (#2) 
 
 
 
 
 
  哈哈，我的多图预览加上了，不过估计你也不需要了，不过还是通知你一声  
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:&amp;amp;nbsp;&amp;quot;zoubeihua&amp;quot;<notifications@github.com&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2020年6月4日(星期四) 中午12:45  
  收件人:&amp;amp;nbsp;&amp;quot;heyongsheng/hevue-img-preview&amp;quot;<hevue-img-preview@noreply.github.com&amp;amp;gt;;  
  抄送:&amp;amp;nbsp;&amp;quot;落叶&amp;quot;<1378431028@qq.com&amp;amp;gt;;&amp;quot;Comment&amp;quot;<comment@noreply.github.com&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [heyongsheng/hevue-img-preview] 能多张图片预览吗? (#2)  
   
   
   
   
   
      
  抱歉，这个暂时不支持，这周末有时间我会加上这个功能  
   期待  
      
  —  
  You are receiving this because you commented.  
  Reply to this email directly, view it on GitHub, or unsubscribe.  
 &amp;mdash; 
 You are receiving this because you authored the thread. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
&mdash;
